# -*- coding: utf-8 -*-
"""Assigement 483557 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8v1g1yqsmaP7gFpVQsXJfyxZ5uIig0V
"""

!pip install streamlit pyngrok pandas

from pyngrok import ngrok
ngrok.set_auth_token("35qHSJv83t4tz65yJNyscjQ9eq3_6CNzjFiJs3nnMdfQzqNyu")

import os

dirs = ["models", "services", "ui", "data"]
for d in dirs:
    os.makedirs(d, exist_ok=True)

print("Folders created successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/student.py
# # paste the Student class code here (from canvas)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile services/storage_json.py
# # paste JSONStorage code here
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile services/student_manager.py
# # paste StudentManager code here
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ui/app.py
# # paste app.py UI code here
#

# Start Streamlit and expose using ngrok
from pyngrok import ngrok

# Kill previous tunnels
ngrok.kill()

# Start a tunnel for port 8501
public_url = ngrok.connect(8501)
print("Streamlit Public URL:", public_url)

# Start Streamlit app
!streamlit run ui/app.py &>/dev/null &

!ps aux | grep streamlit

!streamlit run ui/app.py &>/dev/null &

from pyngrok import ngrok

# Kill any previous tunnels
ngrok.kill()

# Start a new tunnel for port 8501
public_url = ngrok.connect(8501)
print("Your Streamlit public URL:", public_url)

!tail -n 20 ~/.streamlit/logs/streamlit.log

# Install dependencies
!pip install streamlit pyngrok pandas

# Import libraries
from pyngrok import ngrok
import os

# Kill any previous tunnels
ngrok.kill()

# Create project structure
dirs = ["models", "ui", "data"]
for d in dirs:
    os.makedirs(d, exist_ok=True)

# Create minimal Streamlit app for testing
app_code = """
import streamlit as st

st.title('🎓 Student Management System')
st.write('App is running successfully!')
"""

with open("ui/app.py", "w") as f:
    f.write(app_code)

# Start ngrok tunnel
public_url = ngrok.connect(8501)
print("Streamlit public URL:", public_url)

# Start Streamlit
get_ipython().system_raw("streamlit run ui/app.py &")

# ==============================
# 1️⃣ Install dependencies
# ==============================
!pip install streamlit pyngrok pandas --quiet

# ==============================
# 2️⃣ Setup folder structure
# ==============================
import os

folders = ["models", "ui", "data"]
for f in folders:
    os.makedirs(f, exist_ok=True)

# ==============================
# 3️⃣ Write Python files
# ==============================

# models/student.py
student_code = """
class Student:
    def __init__(self, name, roll, grade):
        self.name = name
        self.roll = roll
        self.grade = grade

    def to_dict(self):
        return {
            "name": self.name,
            "roll": self.roll,
            "grade": self.grade
        }
"""
with open("models/student.py", "w") as f:
    f.write(student_code)

# models/manager.py
manager_code = """
import json
import os
from models.student import Student

DATA_FILE = "data/students.json"

class StudentManager:
    def __init__(self):
        os.makedirs("data", exist_ok=True)
        if not os.path.exists(DATA_FILE):
            with open(DATA_FILE, "w") as f:
                json.dump([], f)
        self.students = self.load_data()

    def load_data(self):
        with open(DATA_FILE, "r") as f:
            return json.load(f)

    def save_data(self):
        with open(DATA_FILE, "w") as f:
            json.dump(self.students, f, indent=4)

    def add_student(self, student):
        self.students.append(student.to_dict())
        self.save_data()

    def get_students(self):
        return self.students

    def search_student(self, roll):
        for s in self.students:
            if s["roll"] == roll:
                return s
        return None

    def update_student(self, roll, new_name, new_grade):
        for s in self.students:
            if s["roll"] == roll:
                s["name"] = new_name
                s["grade"] = new_grade
                self.save_data()
                return True
        return False

    def delete_student(self, roll):
        for s in self.students:
            if s["roll"] == roll:
                self.students.remove(s)
                self.save_data()
                return True
        return False
"""
with open("models/manager.py", "w") as f:
    f.write(manager_code)

# ui/app.py
app_code = """
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import streamlit as st
from models.manager import StudentManager
from models.student import Student

manager = StudentManager()

st.title("🎓 Student Management System")

menu = st.sidebar.selectbox(
    "Menu",
    ["Add Student", "View Students", "Search Student", "Update Student", "Delete Student"]
)

if menu == "Add Student":
    st.subheader("➕ Add New Student")
    name = st.text_input("Name")
    roll = st.text_input("Roll Number")
    grade = st.text_input("Grade")
    if st.button("Add Student"):
        student = Student(name, roll, grade)
        manager.add_student(student)
        st.success("Student added successfully!")

elif menu == "View Students":
    st.subheader("📋 All Students")
    students = manager.get_students()
    st.table(students)

elif menu == "Search Student":
    st.subheader("🔍 Search Student by Roll Number")
    roll = st.text_input("Enter Roll Number")
    if st.button("Search"):
        student = manager.search_student(roll)
        if student:
            st.write(student)
        else:
            st.error("Student not found.")

elif menu == "Update Student":
    st.subheader("✏️ Update Student")
    roll = st.text_input("Enter Roll Number to Update")
    new_name = st.text_input("New Name")
    new_grade = st.text_input("New Grade")
    if st.button("Update"):
        updated = manager.update_student(roll, new_name, new_grade)
        if updated:
            st.success("Student updated.")
        else:
            st.error("Student not found.")

elif menu == "Delete Student":
    st.subheader("🗑️ Delete Student")
    roll = st.text_input("Enter Roll Number")
    if st.button("Delete"):
        deleted = manager.delete_student(roll)
        if deleted:
            st.success("Student deleted.")
        else:
            st.error("Student not found.")
"""
with open("ui/app.py", "w") as f:
    f.write(app_code)

# data/students.json
with open("data/students.json", "w") as f:
    f.write("[]")

# ==============================
# 4️⃣ Start ngrok + Streamlit
# ==============================
from pyngrok import ngrok

# Kill previous tunnels
ngrok.kill()

# Start tunnel
public_url = ngrok.connect(8501)
print("🔗 Streamlit Public URL:", public_url)

# Start Streamlit
get_ipython().system_raw("streamlit run ui/app.py &")

import json

def load_students(file_path="students.json"):
    try:
        with open(file_path, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_students(students, file_path="students.json"):
    with open(file_path, "w") as f:
        json.dump(students, f, indent=4)

def validate_name(name):
    return isinstance(name, str) and len(name.strip()) > 0

def validate_age(age):
    return isinstance(age, int) and 5 <= age <= 100

def validate_grade(grade):
    return grade in ["A", "B", "C", "D", "F"]

def filter_by_grade(students, grade):
    return [s for s in students if s.get("grade") == grade]

def filter_by_age(students, min_age=None, max_age=None):
    return [s for s in students if (min_age is None or s.get("age") >= min_age)
                                  and (max_age is None or s.get("age") <= max_age)]

# Create services directory if it doesn't exist
import os
os.makedirs("services", exist_ok=True)

# Write the storage.py file
storage_code = '''
import json

def load_students(file_path="data/students.json"):
    try:
        with open(file_path, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return []

def save_students(students, file_path="data/students.json"):
    with open(file_path, "w") as f:
        json.dump(students, f, indent=4)
'''
with open("services/storage.py", "w") as f:
    f.write(storage_code)

# Write the validation.py file
validation_code = '''
def validate_name(name):
    return isinstance(name, str) and len(name.strip()) > 0

def validate_age(age):
    return isinstance(age, int) and 5 <= age <= 100

def validate_grade(grade):
    return grade in ["A", "B", "C", "D", "F"]
'''
with open("services/validation.py", "w") as f:
    f.write(validation_code)

# Write the filters.py file
filters_code = '''
def filter_by_grade(students, grade):
    return [s for s in students if s.get("grade") == grade]

def filter_by_age(students, min_age=None, max_age=None):
    return [s for s in students if (min_age is None or s.get("age") >= min_age)
                                  and (max_age is None or s.get("age") <= max_age)]
'''
with open("services/filters.py", "w") as f:
    f.write(filters_code)


# Now try importing and using the functions
from services.storage import load_students, save_students
from services.validation import validate_name, validate_age
from services.filters import filter_by_grade, filter_by_age

students = load_students()
print("Modules created and imports successful.")